name: Frédéric CANAUD
bio: Etudiant en 2ème année de DUT Informatique
lang: fr

source: src
destination: _site
strict_front_matter: true

collections:
    school_projects:
        output: true
        permalink: /ecole/:title/
        sort_by: date
    pro_projects:
        output: true
        permalink: /entreprise/:title/
        sort_by: date
    projects:
        output: true
        permalink: /projet/:title/
        sort_by: date
    companies:
        sort_by: date
    formations:
        sort_by: date
    certifications:
        sort_by: date

# twitter summary info
description: Frédéric CANAUD, étudiant en 2ème année en DUT Informatique à Limoges

# Main picture
picture: profile.png

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: false
resume-url: assets/CV.pdf

permalink: /:categories/:title/

# if you don't have any of social below, comment the line
facebook: frederic.canaud
twitter: airmethe
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: 11128157349
github: FredericCanaud
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 6187576/sylvain
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: frederic.canaud@etu.unilim.fr

authors:
    sylvainmetayer:
        name: Frédéric CANAUD
        bio: Etudiant en 2ème année de DUT Informatique
        picture: profile.png
        twitter: Airmethe
        email: frederic.canaud@etu.unilim.fr

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog, projet]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: false

jekyll-mentions:
    base_url: https://github.com

rel_me:
- https://github.com/FredericCanaud
- https://twitter.com/Airmethe

# BUILD SETTINGS
exclude:
    - "travis.sh"
    - "Rakefile"
    - "README.md"
    - "Gemfile"
    - "Gemfile.lock"
    - "netlify.toml"
    - "github_travis.enc"
    - "vendor"
    - "Makefile"
    - "docker-compose.yml"

sass:
    sass_dir: _sass
    style: compressed # possible values: nested expanded compact compressed

url: https://fredericcanaud.github.io
production_url: https://fredericcanaud.github.io

compress_html:
    ignore:
        envs:
        - development
        - stage

highlighter: rouge

assets:
    source_maps: false # false on JEKYLL_ENV=production
    destination: "/assets"
    compression: true # true on JEKYLL_ENV=production
    gzip: true
    defaults:
        js: { integrity: true } # true on JEKYLL_ENV=production
        css: { integrity: true } # true on JEKYLL_ENV=production
        img: { integrity: true } # true on JEKYLL_ENV=production
    sources:
        - _assets/css
        - _assets/fonts
        - _assets/images
        - _assets/images/favicon
        - _assets/images/projets
        - _assets/videos
        - _assets/js
        - _assets/_sass
        - _assets/_sass/base
        - _assets/_sass/components
        - _assets/_sass/pages
